let text = [
  "Every day is taco ipsum tuesday. Can you put some peppers and onions on that? You see, the refried beans are really just the adhesive necessary to apply the soft tortilla to the hard taco shell. TACOS!! Tacos for breakfast, lunch and dinner. Side of rice and beans, please. These tacos are lit. I think I've overdosed on tacos. Let's do a beef and a chicken, and one with both. It's raining tacos, from out of the sky, tacos, don't even ask why.",

  "Tacos al pastor made with adobada meat. Does guac cost extra? Side of rice and beans, please. It's taco time all the time. Black or pinto beans? Tacos dorados called flautas, or taquitos, for which the tortillas are filled with pre-cooked shredded chicken, beef or barbacoa, rolled into an elongated cylinder and deep-fried until crisp. Tacos dorados called flautas, or taquitos, for which the tortillas are filled with pre-cooked shredded chicken, beef or barbacoa, rolled into an elongated cylinder and deep-fried until crisp.",

  "Tacos dorados called flautas, or taquitos, for which the tortillas are filled with pre-cooked shredded chicken, beef or barbacoa, rolled into an elongated cylinder and deep-fried until crisp. Make it a double there pal. Pico de gallo, on the side please. Josh's taco shack is the best taco shack. Add in a few el Pastor with guac and diced onions. Tacos, tacos, tacos. Um, Tabasco? No thanks, do you have any Cholula? CARNE ASADA!! Burritos are very tasty. Burritos are very tasty. Can you put some peppers and onions on that?",

  "These tacos are lit. I've been following that taco truck around all day. Um, Tabasco? No thanks, do you have any Cholula? Black or pinto beans? 50 cent tacos! I'll take 30. Black or pinto beans? It's long been rumored that the chupacabra is really just a crazed man who's local taco shop went out of business. I've been following that taco truck around all day. These tacos are lit. Make it a double there pal. Burritos are very tasty. These tacos are lit. I think I've overdosed on tacos.",

  "How do you feel about hard shelled tacos? Shrimp tacos are tasty tacos! If you were a taco, would you eat yourself? How bout a gosh darn quesadilla? I think I've overdosed on tacos. How bout a gosh darn quesadilla? Tacos dorados called flautas, or taquitos, for which the tortillas are filled with pre-cooked shredded chicken, beef or barbacoa, rolled into an elongated cylinder and deep-fried until crisp. Carne asada on corn tortillas. 50 cent tacos! I'll take 30. You see, the refried beans are really just the adhesive necessary to apply the soft tortilla to the hard taco shell."
];